### ISSUE TITLE
docker and system-docker should have env vars from `rancher.environment`

### ISSUE THREAD

**Issue by imikushin** [rancherio/os#244]
Suppose, we have something useful in `rancher.environment`, e.g.:
```
# rancherctl c get environment
ETCD_ADVERTISE_CLIENT_URLS: http://10.0.2.15:2379,http://10.0.2.15:4001
ETCD_DISCOVERY: https://discovery.etcd.io/978213029d111220b230d0ce0dbc54e7
ETCD_INITIAL_ADVERTISE_PEER_URLS: http://10.0.2.15:2380
ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379,http://0.0.0.0:4001
ETCD_LISTEN_PEER_URLS: http://10.0.2.15:2380
FLANNEL_NETWORK: 10.244.0.0/16
NODE_IP: 10.0.2.15
```
Currently there's just one chance to use these values: starting services on boot. It'd be convenient to have these values injected to containers started with a `docker` or `system-docker` CLI. Of course these should be overridable with real env vars (if available). 

What do you think?

**Comment by ibuildthecloud** [comment]
@imikushin All that would require is that we set the Rancher environment the to shells environment.  Docker already supports the syntax `docker run -e ASDF` where ASDF's value will be pulled from the current env.

I don't think we can set the env by default, because you probably have secret tokens or stuff like that in there that you probably don't want in your env.  But we could add a command like `rancherctl env ...` that executed other command with the env.  For example

`rancherctl env docker run -e NODE_IP ...`

**Comment by imikushin** [comment]
Ideally, I want `docker run -e` to pull env from rancher.environment, but offloading it to `rancherctl` would certainly work too.

**Comment by imikushin** [comment]
So it'd be somewhat like standard `env`? 
+1

**Comment by ibuildthecloud** [comment]
Yep, like that.  PR's welcomed :)

**Comment by imikushin** [comment]
working on it

**Comment by imikushin** [comment]
@ibuildthecloud see PR #246

**Comment by ibuildthecloud** [comment]
I think #246 is the correct approach, I'm closing this issue.  Please reopen if you think something else should be done

**Comment by imikushin** [comment]
OK
