### ISSUE TITLE
how do I create a second network interface ?

### ISSUE THREAD

**Issue by runseb** [rancherio/os#50]
I did not look deep into it, but it seems to be missing some network drivers/device.

**Comment by ibuildthecloud** [comment]
It's basically hard coded to one nic right now.  We will add proper multinic management.  In the time being since it's just docker you can run "docker run --privileged --net=host debian dhclient eth1" or something similar to that.  I haven't actually ran that command and don't know if dhclient is in that image by default.

**Comment by ailispaw** [comment]
I put another config for eth1 into /etc/network/interface like debian.

```
$ cat /etc/network/interfaces
# Configure Loopback
auto lo
iface lo inet loopback

#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth1
iface eth1 inet static
      address 192.168.33.10
      netmask 255.255.255.0
#VAGRANT-END
```

It may need `ifdown` and `ifup` before and after modification.

**Comment by imikushin** [comment]
I guess this one is fixed in v0.1.2:
I've just added another (virtio) NIC to my RancherOS VM in VirtualBox GUI, turned the VM on and it was working, configured with DHCP as expected.

**Comment by ibuildthecloud** [comment]
Yes this was fixed.  We programmed a new component to handle NIC IP configuration.  I'd like to keep this issue open until we document the configuration of it.  The default configuration is that any eth* automatically gets DHCP applied.

@wlan0 Can you update the README with instructions for the netconf configuration in rancher.yml

**Comment by imikushin** [comment]
I've just tried the same thing that just worked for me in v0.1.2 (simply adding another NIC) and it didn't work: `eth1` interface was unconfigured and down. 

That's all right. By adding the necessary config (as described here: https://github.com/rancherio/os/blob/master/docs/config.md) I got the second NIC up and configured with DHCP on boot as desired. `/var/lib/rancher/conf/rancher.yml`:
```yml
network:
  interfaces:
    eth*:
      dhcp: true
```
Would it make sense as the default? So that newly added NICs just work from the start.

**Comment by deniseschannon** [comment]
In v0.3.0, this is definitely fixed. Please re-open if still having issues.

**Comment by imikushin** [comment]
@deniseschannon this is still an issue in v0.3.0 and v0.3.1 RCs. Repro: just add another NIC.
```
./scripts/run -net nic,vlan=1,model=virtio -net user,vlan=1,net=172.17.128.0/24
```
Then look at `ip link` having sshed into the VM:
```
# ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: docker-sys: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue 
    link/ether 5e:a0:10:3e:78:09 brd ff:ff:ff:ff:ff:ff
3: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether 52:54:00:12:34:56 brd ff:ff:ff:ff:ff:ff
4: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 52:54:00:12:34:57 brd ff:ff:ff:ff:ff:ff
5: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue 
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
7: veth58b68aa: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 
    link/ether 66:2d:aa:7b:cd:e2 brd ff:ff:ff:ff:ff:ff
```
Here, `eth1` NIC is down.

**Comment by deniseschannon** [comment]
@ibuildthecloud, see @imikushin's comment on how it's not fixed yet. It looks like he's put in a PR for it.

**Comment by ibuildthecloud** [comment]
I'm closing as per https://github.com/rancherio/os/pull/282#issuecomment-101085569
